// OllamaWire — Codable shapes for Ollama's `/api/generate` endpoint.
//
// Tier 1 portable. Pure Foundation. These types are the wire-format
// boundary; `OllamaProvider` converts to/from `AIRequest` /
// `AIResponse`. `Codable` here makes sense — there's a single wire
// format (Ollama's HTTP API) and these structs map one-for-one to
// it. Contrast with `AIRequest` / `AIResponse`, which are the
// provider-agnostic types and intentionally NOT `Codable`.
//
// API reference: https://github.com/ollama/ollama/blob/main/docs/api.md
//
// We target `/api/generate` with `stream: false` for the simplest
// non-streaming completion. Streaming and the chat-shaped
// `/api/chat` endpoint are future surfaces.

import Foundation

/// Request body for `POST /api/generate`. Field names match
/// Ollama's exact JSON keys; rename via CodingKeys if Ollama
/// changes their wire shape (rather than letting Swift's
/// auto-CodingKey transformation drift).
struct OllamaGenerateRequest: Encodable, Equatable {
    /// The model name (`"llama3"`, `"phi3:mini"`, etc.).
    let model: String

    /// User prompt. Maps from ``AIRequest/userPrompt``.
    let prompt: String

    /// Optional system prompt. Maps from ``AIRequest/systemPrompt``.
    let system: String?

    /// Always `false` for the first slice. Streaming is a
    /// follow-up — the response shape is different (NDJSON
    /// stream vs. single JSON object) and the AIProvider
    /// protocol doesn't expose streaming yet.
    let stream: Bool

    /// Optional generation parameters. Ollama nests these under
    /// `"options"` rather than as siblings. Nil omits the key
    /// entirely so Ollama uses its model-side defaults.
    let options: Options?

    struct Options: Encodable, Equatable {
        /// Sampling temperature. Maps from
        /// ``AIRequest/temperature``.
        let temperature: Double?

        /// Maximum tokens to predict. Maps from
        /// ``AIRequest/maxTokens``. Ollama's key is `num_predict`.
        let numPredict: Int?

        enum CodingKeys: String, CodingKey {
            case temperature
            case numPredict = "num_predict"
        }
    }
}

/// Response body from `POST /api/generate` with `stream: false`.
///
/// We model the fields we use; Ollama emits more (token counts,
/// load timings, model digest, etc.) — the decoder happily
/// ignores them.
struct OllamaGenerateResponse: Decodable, Equatable {
    /// The generated text. May include leading/trailing
    /// whitespace; the provider trims before returning to
    /// callers.
    let response: String

    /// Always `true` in non-streaming mode. Tracked so we can
    /// detect format drift (an Ollama upgrade returning
    /// `done: false` for non-streaming would be a wire-shape
    /// regression we'd want to throw on).
    let done: Bool

    /// Why generation stopped. Common values: `"stop"` (model
    /// emitted EOS), `"length"` (hit `num_predict`),
    /// `"load"` (model load failure mid-stream — rare).
    /// Ollama added this field in v0.3.x; older versions omit
    /// it, which is why it's optional.
    let doneReason: String?

    /// Tokens consumed by the prompt (system + user combined).
    /// Optional — Ollama reports it but technically can omit
    /// on partial responses.
    let promptEvalCount: Int?

    /// Tokens generated by the model.
    let evalCount: Int?

    enum CodingKeys: String, CodingKey {
        case response, done
        case doneReason = "done_reason"
        case promptEvalCount = "prompt_eval_count"
        case evalCount = "eval_count"
    }
}
